name: release

on:
  push:
    tags:
      - "v*.*.*"
  # schedule:
  #   - cron: "0 0 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            repository: 'Conflux-Chain/conflux-rust'
            fetch-depth: 0
            